---
- name: Setup files and SR
  hosts: '{{ target | default("all") }}'

  tasks:

  - name: Copy other tools 
    copy:
      src: "../files/{{ item }}"
      dest: "/opt/tools/{{ item }}"
      owner: root
      mode: 0755
    with_items:
      - up.py
      - up2.py
      - cmds.sh
      - after.sh
      - cleantrash.sh

  - name: Get TS server binary
    get_url:
      url: https://github.com/streamingriver/ts-server/releases/download/v0.4/ts-server_linux_amd64
      dest: /opt/tools/ts-server_linux_amd64
      mode: 0755
      owner: root

  - name: Get hls-proxy server binary
    get_url:
      url: https://github.com/streamingriver/go-hls-proxy/releases/download/v0.1/hls-proxy_linux_amd64
      dest: /opt/tools/hls-proxy_linux_amd64
      mode: 0755
      owner: root

  - name: Get registry server binary
    get_url:
      url: https://github.com/streamingriver/go-frontend/releases/download/v0.2/frontend_linux_amd64
      dest: /opt/tools/frontend_linux_amd64
      mode: 0755
      owner: root

  - name: Get SR release
    git:
      repo: 'https://github.com/streamingriver/vms'
      dest: /var/www/sr 